/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package templategenerator;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Properties;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author natehindman
 */
public class TemplateWindow extends javax.swing.JFrame {

    
    /**
     * Creates new form NewJFrame
     */
    public TemplateWindow() {
            setup();
            initComponents();
            jComboBox1.setModel(new DefaultComboBoxModel(files));
            setResizable(false);
    }
    
    private void setup(){
        try {
            Properties prop = new Properties();
            FileReader read = new FileReader("filePath.properties");
            prop.load(read);
            if(SystemUtils.IS_OS_WINDOWS)
                folder = new File(prop.getProperty("testResourceFilesWin"));
            else if(SystemUtils.IS_OS_MAC)
                folder = new File(prop.getProperty("testResourceFilesMac"));
            fileList = folder.listFiles();
        } catch (IOException ex) {
            System.out.println("File retrieval failed.");
        }
        
        files = new String[fileList.length];
        
        for(int i = 0; i < fileList.length; i++){
            files[i] = fileList[i].getName();
        }
        
        if(fileList!= null){
            for(File file : fileList){
                System.out.println(file.getName());
            }
        }
    }
    
    private String[] dataFileToString(File inFile){
        String[] data = new String[50];
        String lastData;
        int i = 0;
        
        try {
            FileReader readIn = new FileReader(inFile);
            BufferedReader readFile = new BufferedReader(readIn);
            
            lastData = readFile.readLine();
            
            while(lastData != null && lastData != ""){
                
                if(i >= data.length){
                    
                    String[] temp = new String[data.length + 1];
                    
                    for(int j = 0; j < data.length; j++){
                        temp[j] = data[j];
                    }
                    
                    data = temp;
                    
                }
                
                
                data[i] = lastData;
                lastData = readFile.readLine();
                i++;
            }    
            
        } catch (IOException ex) {
        }
        
        return data;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Template Generator");

        jTextField1.setToolTipText("Enter file name");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("File Name:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Starting Serial Number");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quantity");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Comments");

        jScrollPane1.setAutoscrolls(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Data File");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String inputName = jTextField1.getText();
        String comments = jTextArea1.getText();
        double numberinput = Double.parseDouble(jTextField2.getText());
        double quantity = Double.parseDouble(jTextField3.getText());
        File writeFile = new File(inputName + ".csv");
        String serialText;
        try {
            if(!"".equals(inputName)
                    && writeFile.exists() != true 
                    && Double.parseDouble(jTextField3.getText()) > 0
                    && Double.parseDouble(jTextField2.getText()) > 0){ // so the user can't screw up and make a blank csv by accident
                
                FileWriter fileWriter = new FileWriter(writeFile, true); 
                BufferedWriter buffer = new BufferedWriter(fileWriter);
                PrintWriter printWriter = new PrintWriter(fileWriter);
                printWriter.print("category path = Root\\Kit Serial Numbers\n"
                            + "Miguel Cantu,,,,Chris Rucker (Quality),,,,,,Chris Hoagland,,,,,,,,,,,,,,,,,,,,\n"                      
                            +"Serial #,,Part #,,Capacitance,,Esr,,Leakage,,Anode Lot,,,,,Cathode Lot,,Tantalum Lot,,Header Glassing,,,,,,,,,,Comments,\n"
                            +",,,,,,,,,,,,,,,,,,,,,,,,,,,,," + comments + ",\n"
                            +",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n"
                            +",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n"
                            +",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n"
                            +",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n"
                            +",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n"
                            +",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n"
                            +",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n"
                            +",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n"
                            +",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n"
                            +",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n"
                            + "Entered Data,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n"
                            + ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n"
                            + "Serial #,,Part #,,Capacitance,,Esr,,Leakage,,Anode Lot,,,,,Cathode Lot,,Tantalum Lot,,Header Glassing,,"
                            +"Teflon Spacer 1,,Teflon Spacer 2,,Teflon Spacer 3,,Teflon Lot #,,Comments,\n");
                for(Double number = numberinput; number < quantity + numberinput; number++){
                    serialText = String.valueOf(number).indexOf(".") < 0 ? String.valueOf(number) : String.valueOf(number).replaceAll("0*$", "").replaceAll("\\.$", "");
                    printWriter.print(serialText + ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n");
                }
                
                printWriter.print(",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n");
                printWriter.print("Data Sheet,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n");
                for(String line : dataFileToString(fileList[jComboBox1.getSelectedIndex()])){
                    if(line != null)
                        printWriter.print(line + "\n");
                }
         
                printWriter.close();
                jLabel2.setText("Created " + inputName + ".csv");
                 
         
         
            }
            else if (Double.parseDouble(jTextField3.getText()) < 1)
                jTextField3.setText("Please enter a valid quantity.");
            else if (Double.parseDouble(jTextField2.getText()) > 0)
                jTextField2.setText("Please enter a valid serial.");
            else if (writeFile.exists() == true)
                jTextField1.setText("File name taken.");
                
    } catch (IOException ex) {
                jLabel2.setText("Cannot write file.");
    }
        
            //dd your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemplateWindow().setVisible(true);
            }
        });
    }
    
    private File folder;
    private File[] fileList;
    private String[] files;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
